[package]
name = "git-lineage"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
gix = "0.66"
tokio = { version = "1.0", features = ["full"] }
syntect = "5.2"
tui-tree-widget = "0.22"
similar = "2.6"
fuzzy-matcher = "0.3"
